<Type Name="DtsNoTaskAssignedException" FullName="Microsoft.SqlServer.Dts.Runtime.DtsNoTaskAssignedException">
  <TypeSignature Language="C#" Value="public sealed class DtsNoTaskAssignedException : Microsoft.SqlServer.Dts.Runtime.DtsException" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi serializable sealed beforefieldinit DtsNoTaskAssignedException extends Microsoft.SqlServer.Dts.Runtime.DtsException" />
  <TypeSignature Language="DocId" Value="T:Microsoft.SqlServer.Dts.Runtime.DtsNoTaskAssignedException" />
  <AssemblyInfo>
    <AssemblyName>Microsoft.SqlServer.ManagedDTS</AssemblyName>
    <AssemblyVersion>14.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>Microsoft.SqlServer.Dts.Runtime.DtsException</BaseTypeName>
  </Base>
  <Interfaces />
  <Docs>
    <summary>Die Ausnahme, die ausgelöst wird, um einen internen Fehler anzugeben, der auftritt, wenn ein verwalteter Wrapper für ein systemeigenes Objekt verwendet wird, das nicht den richtigen Typ aufweist.</summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members />
</Type>
